04/config/routes.rb
Rails.application.routes.draw do
  resources :raw_words
  resources :social_nodes
  get 'home/index'

  resources :hist_friends
  resources :word_friends
  resources :words
  resources :histograms
  resources :word_lengths
  get 'hello_world/index'
  # root 'hello_world#index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

04/app/models/raw_word.rb
class RawWord < ApplicationRecord
  belongs_to :word
end

04/app/controllers/raw_words_controller.rb
class RawWordsController < ApplicationController
  before_action :set_raw_word, only: [:show, :edit, :update, :destroy]

  # GET /raw_words
  # GET /raw_words.json
  def index
    @raw_words = RawWord.all
  end

  # GET /raw_words/1
  # GET /raw_words/1.json
  def show
  end

  # GET /raw_words/new
  def new
    @raw_word = RawWord.new
  end

  # GET /raw_words/1/edit
  def edit
  end

  # POST /raw_words
  # POST /raw_words.json
  def create
    @raw_word = RawWord.new(raw_word_params)

    respond_to do |format|
      if @raw_word.save
        format.html { redirect_to @raw_word, notice: 'Raw word was successfully created.' }
        format.json { render :show, status: :created, location: @raw_word }
      else
        format.html { render :new }
        format.json { render json: @raw_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /raw_words/1
  # PATCH/PUT /raw_words/1.json
  def update
    respond_to do |format|
      if @raw_word.update(raw_word_params)
        format.html { redirect_to @raw_word, notice: 'Raw word was successfully updated.' }
        format.json { render :show, status: :ok, location: @raw_word }
      else
        format.html { render :edit }
        format.json { render json: @raw_word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /raw_words/1
  # DELETE /raw_words/1.json
  def destroy
    @raw_word.destroy
    respond_to do |format|
      format.html { redirect_to raw_words_url, notice: 'Raw word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_raw_word
      @raw_word = RawWord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def raw_word_params
      params.require(:raw_word).permit(:name, :is_test_case, :word_id)
    end
end

04/app/helpers/raw_words_helper.rb
module RawWordsHelper
end

04/app/views/raw_words/_form.html.erb
<%= form_for(raw_word) do |f| %>
  <% if raw_word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(raw_word.errors.count, "error") %> prohibited this raw_word from being saved:</h2>

      <ul>
      <% raw_word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :is_test_case %>
    <%= f.text_field :is_test_case %>
  </div>

  <div class="field">
    <%= f.label :word_id %>
    <%= f.text_field :word_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

04/app/views/raw_words/edit.html.erb
<h1>Editing Raw Word</h1>

<%= render 'form', raw_word: @raw_word %>

<%= link_to 'Show', @raw_word %> |
<%= link_to 'Back', raw_words_path %>

04/app/views/raw_words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Raw Words</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is test case</th>
      <th>Soc Net Size</th>

      <th>Word Id</th>
      <th>Word</th>
      <th>Histogram</th>
      <th>Traversed Ids</th>
      <th>Word Friends</th>
      <th>Soc Net Word Names</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @raw_words.each do |raw_word| %>
      <tr>
        <td><%= raw_word.name %></td>
        <td><%= raw_word.is_test_case %></td>
        <td><%= raw_word.word.soc_net_size if raw_word.word %></td>

        <td><%= raw_word.word[:id] if raw_word.word %></td>
        <td><%= raw_word.word[:name] if raw_word.word %></td>
        <td><%= raw_word.word.histogram[:hist] if raw_word.word.histogram %></td>
        <td><%= raw_word.word.traversed_ids if raw_word.word %></td>
        <td><%= raw_word.word.word_friends_word_names if raw_word.word %></td> <!--word_to_friends-->
        <td><%= raw_word.word.in_soc_net_names if raw_word.word %></td>

        <td><%= link_to 'Show', raw_word %></td>
        <td><%= link_to 'Edit', edit_raw_word_path(raw_word) %></td>
        <td><%= link_to 'Destroy', raw_word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Raw Word', new_raw_word_path %>

04/app/views/raw_words/new.html.erb
<h1>New Raw Word</h1>

<%= render 'form', raw_word: @raw_word %>

<%= link_to 'Back', raw_words_path %>

04/app/views/raw_words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @raw_word.name %>
</p>

<p>
  <strong>Is test case:</strong>
  <%= @raw_word.is_test_case %>
</p>

<p>
  <strong>Word:</strong>
  <%= @raw_word.word %>
</p>

<%= link_to 'Edit', edit_raw_word_path(@raw_word) %> |
<%= link_to 'Back', raw_words_path %>