04/config/routes.rb
Rails.application.routes.draw do
  resources :raw_words
  resources :social_nodes
  get 'home/index'

  resources :hist_friends
  resources :word_friends
  resources :words
  resources :histograms
  resources :word_lengths
  get 'hello_world/index'
  # root 'hello_world#index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

04/app/models/word_length.rb
class WordLength < ApplicationRecord
  has_many :words #, inverse_of: :word_length
  has_many :histograms #, inverse_of: :word_length
end

04/app/controllers/word_lengths_controller.rb
class WordLengthsController < ApplicationController
  before_action :set_word_length, only: [:show, :edit, :update, :destroy]

  # GET /word_lengths
  # GET /word_lengths.json
  def index
    @word_lengths = WordLength.order(:length).all
  end

  # GET /word_lengths/1
  # GET /word_lengths/1.json
  def show
  end

  # GET /word_lengths/new
  def new
    @word_length = WordLength.new
  end

  # GET /word_lengths/1/edit
  def edit
  end

  # POST /word_lengths
  # POST /word_lengths.json
  def create
    @word_length = WordLength.new(word_length_params)

    respond_to do |format|
      if @word_length.save
        format.html { redirect_to @word_length, notice: 'Word length was successfully created.' }
        format.json { render :show, status: :created, location: @word_length }
      else
        format.html { render :new }
        format.json { render json: @word_length.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /word_lengths/1
  # PATCH/PUT /word_lengths/1.json
  def update
    respond_to do |format|
      if @word_length.update(word_length_params)
        format.html { redirect_to @word_length, notice: 'Word length was successfully updated.' }
        format.json { render :show, status: :ok, location: @word_length }
      else
        format.html { render :edit }
        format.json { render json: @word_length.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /word_lengths/1
  # DELETE /word_lengths/1.json
  def destroy
    @word_length.destroy
    respond_to do |format|
      format.html { redirect_to word_lengths_url, notice: 'Word length was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word_length
      @word_length = WordLength.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_length_params
      params.require(:word_length).permit(:length)
    end
end

04/app/helpers/word_lengths_helper.rb
module WordLengthsHelper
end

04/app/views/word_lengths/_form.html.erb
<%= form_for(word_length) do |f| %>
  <% if word_length.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word_length.errors.count, "error") %> prohibited this word_length from being saved:</h2>

      <ul>
      <% word_length.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :length %>
    <%= f.number_field :length %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

04/app/views/word_lengths/edit.html.erb
<h1>Editing Word Length</h1>

<%= render 'form', word_length: @word_length %>

<%= link_to 'Show', @word_length %> |
<%= link_to 'Back', word_lengths_path %>

04/app/views/word_lengths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Word Lengths</h1>

<table>
  <thead>
    <tr>
      <th>Length</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @word_lengths.each do |word_length| %>
      <tr>
        <td><%= word_length.length %></td>
        <td><%= link_to 'Show', word_length %></td>
        <td><%= link_to 'Edit', edit_word_length_path(word_length) %></td>
        <td><%= link_to 'Destroy', word_length, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word Length', new_word_length_path %>

04/app/views/word_lengths/new.html.erb
<h1>New Word Length</h1>

<%= render 'form', word_length: @word_length %>

<%= link_to 'Back', word_lengths_path %>

04/app/views/word_lengths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Length:</strong>
  <%= @word_length.length %>
</p>

<p>
  <strong>Histograms:</strong>
  <%= @word_length.histograms.pluck(:hist) %>
</p>

<p>
  <strong>words:</strong>
  <%= @word_length.words.pluck(:name) %>
</p>

<%= link_to 'Edit', edit_word_length_path(@word_length) %> |
<%= link_to 'Back', word_lengths_path %>