04/config/routes.rb
Rails.application.routes.draw do
  resources :raw_words
  resources :social_nodes
  get 'home/index'

  resources :hist_friends
  resources :word_friends
  resources :words
  resources :histograms
  resources :word_lengths
  get 'hello_world/index'
  # root 'hello_world#index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

04/app/models/histogram.rb
class Histogram < ApplicationRecord
  belongs_to :word_length , inverse_of: :histograms
  has_many :words , inverse_of: :histogram

  has_many :hist_from_friends, class_name: "HistFriend", foreign_key: :hist_from_id
  has_many :hist_to_friends, class_name: "HistFriend", foreign_key: :hist_to_id

  serialize :hist

  def hist_from_friends
    HistFriend.where(hist_from: id)
  end

  def self.combine_keys(hist_a, hist_b)
    (hist_a.keys << hist_b.keys).flatten
  end

  def self.delta_hist(hist_a, hist_b)
    delta = {}
    delta_keys = combine_keys(hist_a, hist_b)
    delta_keys.each do |key|
      a = hist_a[key] || 0
      b = hist_b[key] || 0
      delta[key] = b - a
    end
    delta
  end

  def self.delta_trimmed(a_delta_hist)
    a_delta_hist.delete_if { |key, value| value == 0 }
  end

  def self.distance_hist(hist_a, hist_b)
    delta_hist(hist_a, hist_b).values.inject(0) { |sum, v| sum + v.abs }
  end

  def self.length_hist(hist_a)
    hist_a.values.inject(0) { |sum, v| sum + v }
  end

  def self.friends_hist_type(hist_a, hist_b)
    dist = distance_hist(hist_a, hist_b)
    d = delta_hist(hist_a, hist_b)
    dt = delta_trimmed(d)
    key_cnt = dt.keys.count
    if (dist == key_cnt)
      case dist
        when 1
          1 # aka true
        when 2
          dtk = dt.keys
          2 if (dt[dtk[0]] == - dt[dtk[1]]) # aka true
        else
          0 # aka false
      end
    else
      false
    end
  end
end

04/app/controllers/histograms_controller.rb
class HistogramsController < ApplicationController
  before_action :set_histogram, only: [:show, :edit, :update, :destroy]

  # GET /histograms
  # GET /histograms.json
  def index
    @histograms = Histogram.order(:length, :hist).all
  end

  # GET /histograms/1
  # GET /histograms/1.json
  def show
  end

  # GET /histograms/new
  def new
    @histogram = Histogram.new
  end

  # GET /histograms/1/edit
  def edit
  end

  # POST /histograms
  # POST /histograms.json
  def create
    @histogram = Histogram.new(histogram_params)

    respond_to do |format|
      if @histogram.save
        format.html { redirect_to @histogram, notice: 'Histogram was successfully created.' }
        format.json { render :show, status: :created, location: @histogram }
      else
        format.html { render :new }
        format.json { render json: @histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histograms/1
  # PATCH/PUT /histograms/1.json
  def update
    respond_to do |format|
      if @histogram.update(histogram_params)
        format.html { redirect_to @histogram, notice: 'Histogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @histogram }
      else
        format.html { render :edit }
        format.json { render json: @histogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histograms/1
  # DELETE /histograms/1.json
  def destroy
    @histogram.destroy
    respond_to do |format|
      format.html { redirect_to histograms_url, notice: 'Histogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_histogram
      @histogram = Histogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def histogram_params
      params.require(:histogram).permit(:hist, :length, :word_length_id)
    end
end

04/app/helpers/histograms_helper.rb
module HistogramsHelper
end

04/app/views/histograms/_form.html.erb
<%= form_for(histogram) do |f| %>
  <% if histogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(histogram.errors.count, "error") %> prohibited this histogram from being saved:</h2>

      <ul>
      <% histogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hist %>
    <%= f.text_area :hist %>
  </div>

  <div class="field">
    <%= f.label :length %>
    <%= f.number_field :length %>
  </div>

  <div class="field">
    <%= f.label :word_length_id %>
    <%= f.text_field :word_length_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

04/app/views/histograms/edit.html.erb
<h1>Editing Histogram</h1>

<%= render 'form', histogram: @histogram %>

<%= link_to 'Show', @histogram %> |
<%= link_to 'Back', histograms_path %>

04/app/views/histograms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histograms</h1>

<table>
  <thead>
    <tr>
      <th>Hist</th>
      <th>Length</th>
      <th>Word length</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histograms.each do |histogram| %>
      <tr>
        <td><%= histogram.hist %></td>
        <td><%= histogram.length %></td>
        <td><%= histogram.word_length %></td>
        <td><%= link_to 'Show', histogram %></td>
        <td><%= link_to 'Edit', edit_histogram_path(histogram) %></td>
        <td><%= link_to 'Destroy', histogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Histogram', new_histogram_path %>

04/app/views/histograms/new.html.erb
<h1>New Histogram</h1>

<%= render 'form', histogram: @histogram %>

<%= link_to 'Back', histograms_path %>

04/app/views/histograms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hist:</strong>
  <%= @histogram.hist %>
</p>

<p>
  <strong>Length:</strong>
  <%= @histogram.length %>
</p>

<p>
  <strong>Word length:</strong>
  <%= @histogram.word_length %>
</p>

<%= link_to 'Edit', edit_histogram_path(@histogram) %> |
<%= link_to 'Back', histograms_path %>